version: '3.1'

services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      -  "5672:5672"
      -  "15672:15672"
  service-a:
    image: service-a
    depends_on:
      - rabbitmq
    ports:
      - 8080:8080
    restart: on-failure